name: nbconvert_docs
channels:
  - conda-forge
dependencies:
- python==3.7
- pandoc
- nbformat
- jupyter_client
- ipython
- sphinx>=1.5.1
- sphinx_rtd_theme
- tornado
- entrypoints
- ipykernel
- pip
- pip:
    - nbsphinx>=0.7.1
