language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=dist
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=manifest
install:
  - pip install tox
script:
  - tox -e $TOXENV
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TOXENV = "py36" &&
    coverage xml -i
  - test $TRAVIS_BRANCH = "master" &&
    test $TOXENV = "py36" &&
    codecov
